In [1]:
train_path  = "./tmp/concat_train.csv"
test_path = "./tmp/concat_test.csv"

In [25]:
from sklearn.metrics import precision_recall_curve,classification_report, confusion_matrix
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [4]:
train_df = pd.read_csv(train_path)
test_df = pd.read_csv(test_path)

In [13]:
np.unique(train_df.y_pred_score.values)

array([1.39214211e-04, 1.43044538e-04, 1.45606474e-04, 1.48155223e-04,
       1.51391901e-04, 1.54041905e-04, 1.58632217e-04, 1.80470898e-04,
       1.88757177e-04, 1.92061106e-04, 8.84537576e-04, 9.59731201e-04,
       1.07630194e-03, 1.21886405e-03, 1.26915103e-03, 1.19797480e-02,
       4.87388233e-01, 9.34480919e-01, 9.46795655e-01, 9.68940718e-01,
       9.93072946e-01, 9.95585013e-01, 9.90000000e+01])

In [21]:
train_df.head()

anomaly                                            line_id  \
0        0  105_dnm_tmp_NlZyB#sum_iUserNum_300#20190623_16...   
1        0  105_dnm_tmp_NlZyB#sum_iUserNum_300#20190623_16...   
2        0  105_dnm_tmp_NlZyB#sum_iUserNum_300#20190623_16...   
3        0  105_dnm_tmp_NlZyB#sum_iUserNum_300#20190623_16...   
4        0  105_dnm_tmp_NlZyB#sum_iUserNum_300#20190623_16...   

            timestamps     value Hour_Minute        Date  y_pred  y_pred_score  
0  2019-06-08 00:00:00  901283.0    00:00:00  2019-06-08      99          99.0  
1  2019-06-08 00:05:00  887988.0    00:05:00  2019-06-08      99          99.0  
2  2019-06-08 00:10:00  873448.0    00:10:00  2019-06-08      99          99.0  
3  2019-06-08 00:15:00  859882.0    00:15:00  2019-06-08      99          99.0  
4  2019-06-08 00:20:00  846373.0    00:20:00  2019-06-08      99          99.0

In [26]:
aa = classification_report(train_df.anomaly, train_df.y_pred)
print(aa)
aa = confusion_matrix(train_df.anomaly, train_df.y_pred)
print(aa)

/Users/stellazhao/anaconda3/envs/py37/lib/python3.7/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [27]:
print(aa)

[[ 25540     83 136004]
 [   289      8   3046]
 [     0      0      0]]


In [28]:
line_id = np.unique(train_df.line_id.values)

In [33]:
df = train_df.copy()
y_pred = []
y_true = []
for l in line_id:
    df_sclie = df[df.line_id == l].copy()
    y_true.extend(list(df_sclie.anomaly.values[-400:]))
    y_pred.extend(list(df_sclie.y_pred.values[-400:]))



In [36]:
aa = classification_report(y_true, y_pred)
print(aa)
aa = confusion_matrix(y_true, y_pred)
print(aa)

              precision    recall  f1-score   support

           0       0.99      1.00      0.99     17769
           1       0.09      0.03      0.05       231

   micro avg       0.98      0.98      0.98     18000
   macro avg       0.54      0.51      0.52     18000
weighted avg       0.98      0.98      0.98     18000

[[17686    83]
 [  223     8]]
